"""
Red Network Plane - Sovereign eBPF/XDP High-Performance Transparent Gateway.
Intercepts driver-level ingress packages, performs tunneling capsules, and rolls back responses.
"""

import os
import sys
import time
import threading
from bcc import BPF
import ctypes
from scapy.all import Ether, IP, UDP, sendp
from rich.console import Console
from rich.table import Table
from rich.live import Live
from rich.align import Align
from rich.panel import Panel

console = Console()

# ───────────────────────────────────────────────────────────────────────
# 🌟 KERNEL BOUNDARY DEFINITIONS (BCC / XDP Driver Layer C Source Code)
# ───────────────────────────────────────────────────────────────────────
XDP_KERNEL_CODE = """
#include <linux/bpf.h>
#include <linux/if_ether.h>
#include <linux/ip.h>
#include <linux/udp.h>

// BPF ring buffer to pass intercepted raw packets up to user-space Python
BPF_PERF_OUTPUT(intercepted_events);

int xdp_gateway_handler(struct xdp_md *ctx) {
    void *data_end = (void *)(long)ctx->data_end;
    void *data     = (void *)(long)ctx->data;

    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return XDP_PASS;

    // Isolate IPv4 standard packets
    if (eth->h_proto != __constant_htons(ETH_P_IP)) return XDP_PASS;

    struct iphdr *ip = (void *)(eth + 1);
    if ((void *)(ip + 1) > data_end) return XDP_PASS;

    // Filter UDP specific streams
    if (ip->protocol != IPPROTO_UDP) return XDP_PASS;

    struct udphdr *udp = (void *)(ip + 1);
    if ((void *)(udp + 1) > data_end) return XDP_PASS;

    // Intercept precise target ingress gateway port (52719)
    if (udp->dest == __constant_htons(52719)) {
        __u32 size = (__u32)(data_end - data);
        
        // Pass the entire wire-level frame metadata up to Python via Perf RingBuffer
        intercepted_events.perf_submit(ctx, &size, sizeof(size));
        
        // CRITICAL INTERCEPTION: Swallow the frame, halting native Linux routing stack
        return XDP_DROP;
    }

    return XDP_PASS;
}
"""

class GatewayConfig:
    INTERFACE = "ens33"
    SERVER_IP = "192.168.211.130"
    SERVER_PORT = 52720
    # Update these target MAC coordinates derived from your local hardware deployment
    GATEWAY_MAC = "00:0c:29:11:11:11" 
    SERVER_MAC  = "00:0c:29:22:22:22"

class GatewayRuntime:
    total_intercepted = 0
    total_reflected = 0
    last_frame_bytes = 0
    system_status = "Booting Hardware Matrix..."

stats = GatewayRuntime()

# Pre-allocate standard L3 UDP outbound socket to flood encapsulated loads to Server 130
udp_tx_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
udp_tx_sock.setsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF, 4 * 1024 * 1024)

def build_centered_ui() -> Align:
    table = Table(show_header=False, expand=True, border_style="bright_red")
    table.add_column("Metric Profile", style="magenta", width=30)
    table.add_column("Live Grid Analytics", style="green", justify="right")

    table.add_row("Data Plane Engine Backend", "Kernel Driver Space XDP Hook")
    table.add_row("Sovereign Lock Status", f"[bold gold1]{stats.system_status}[/bold gold1]")
    table.add_row("Intercepted Wire Signals", f"{stats.total_intercepted:,} Packets")
    table.add_row("L2 Layer Direct Reflections", f"{stats.total_reflected:,} Packets")
    table.add_row("Last Inspected Ingress Mass", f"{stats.last_frame_bytes} Bytes")
    table.add_row("Egress Pipeline Vectors", f"{GatewayConfig.SERVER_IP}:{GatewayConfig.SERVER_PORT}")

    panel = Panel(
        table, 
        title="[bold bright_red]🔥 RED TRANSPARENT XDP GATEWAY[/bold bright_red]", 
        border_style="bright_red",
        width=72
    )
    return Align.center(panel, vertical="middle")

def process_xdp_packet(cpu, data, size):
    """Callback execution triggered dynamically when XDP submits raw frames."""
    try:
        # 1. Parse raw bytes delivered directly from Network Interface Controller
        raw_packet_bytes = ctypes.string_at(data, size)
        stats.last_frame_bytes = len(raw_packet_bytes)
        stats.total_intercepted += 1

        # 2. Encapsulate complete raw byte arrays as payload over standard UDP socket
        udp_tx_sock.sendto(raw_packet_bytes, (GatewayConfig.SERVER_IP, GatewayConfig.SERVER_PORT))
    except Exception:
        pass

def listen_server_responses():
    """Asynchronous L3 Listener hunting for reflected feedback arriving from Server 130."""
    rx_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    rx_sock.bind(("0.0.0.0", 52721)) # Bind to exclusive response coordinate
    
    while True:
        try:
            # Receive de-capsulated response packet generated by server
            constructed_response, _ = rx_sock.recvfrom(4096)
            
            # Reconstruct Ether bound wrapper injecting precise hardware MAC targeting
            reflected_ether_frame = (
                Ether(src=GatewayConfig.GATEWAY_MAC, dst=GatewayConfig.SERVER_MAC) /
                constructed_response
            )
            
            # Force Raw L2 execution bypassing entire Kernel egress barriers
            sendp(reflected_ether_frame, iface=GatewayConfig.INTERFACE, verbose=False)
            stats.total_reflected += 1
        except Exception:
            pass

def main():
    if os.getuid() != 0:
        console.print("[bold red]❌ Critical: Execution requires hardware administrative privileges (root).[/bold red]")
        sys.exit(1)

    stats.system_status = "Compiling BPF Bytecode..."
    bpf_module = BPF(text=XDP_KERNEL_CODE)
    fn = bpf_module.load_func("xdp_gateway_handler", BPF.XDP)
    
    # Secure atomic bind over the network hardware layer
    bpf_module.attach_xdp(GatewayConfig.INTERFACE, fn, 0)
    stats.system_status = "XDP ACTIVE (SOVEREIGN INTERCEPT)"

    # Boot independent runtime thread hunting for reflected streams
    reflection_worker = threading.Thread(target=listen_server_responses, daemon=True)
    reflection_worker.start()

    # Open Kernel Perf Engine mapping ring-buffer arrays natively into Python execution memory
    bpf_module["intercepted_events"].open_perf_buffer(process_xdp_packet)

    with Live(build_centered_ui(), auto_refresh=False, screen=True) as live:
        try:
            while True:
                live.update(build_centered_ui(), refresh=True)
                # Efficient polling cycle yielding execution windows back to system CPU
                bpf_module.perf_buffer_poll(timeout=10)
                time.sleep(0.01)
        except KeyboardInterrupt:
            stats.system_status = "Detaching Drivers..."
            live.update(build_centered_ui(), refresh=True)
        finally:
            # Atomic cleanup sequence resetting Network interface controllers back to default
            bpf_module.remove_xdp(GatewayConfig.INTERFACE, 0)
            console.print("\n[bold green]✅ XDP Hook cleared cleanly. Native kernel routing restored.[/bold green]")

if __name__ == "__main__":
    main()